Implemented .net core version
wojciech12/talk_zero_downtime_deployment_with_kubernetes pull request #3
Opened 2018-11-02 12:57 UTC by meanin

Support for:
- health checks
- readiness checks

Implemented:
- graceful shutdown, (not working at this time, issue [here](https://github.com/dotnet/coreclr/issues/20765))

2018-11-02 14:08 UTC, wojciech12 requested changes

2018-11-02 14:08 UTC, wojciech12 commented on .gitignore
> +## Ignore Visual Studio temporary files, build results, and
Please add prefix demo_net to the .gitignore rules for the C# implementation

2018-11-02 14:08 UTC, wojciech12 commented on demo_net/.dockerignore
> +**/.toolstarget
newline :)

2018-11-08 21:42 UTC, wojciech12 commented on demo_net/ZeroDowntimeDeployment/Middlewares/GracefulShutdownMiddleware.cs
> +    public class GracefulShutdownMiddleware
Could we add more logging and add 5 seconds sleep before we do the graceful shutdown. With 5 seconds sleep, we can test whether the code below works.

2018-11-08 21:44 UTC, wojciech12 commented on demo_net/ZeroDowntimeDeployment/Middlewares/LivenessProbeMiddleware.cs
> +                case "/healthz":
Please also return: OK <hostname> and NOT OK <hostname>.
So, during the demo, it is clear which instances of our demo are unhealthy.

2018-11-09 13:32 UTC, meanin commented
Solution tested on docker interactive. Graceful Shutdown Middleware works as expected. 

Thanks for this journey :)

2018-11-27 14:03 UTC, wojciech12 commented
@meanin  Thank you for your contribution. I will merge it.

2018-11-27 14:03 UTC, merged